#pragma once

#include <stddef.h>

#include "eol_types.h"

typedef enum
{
	EOL_GROUP_NODE = 0,
	EOL_GROUP_GATEWAY,
	EOL_GROUP_SYSTEM,
	EOL_GROUP_COUNT
} EolTestGroup_t;

typedef enum
{
	EOL_N01_BOOT_HEALTH = 0,
	EOL_N02_FIRMWARE_IDENTITY,
	EOL_N03_BOARD_IDENTITY,
	EOL_N04_STARTUP_FAULT,
	EOL_N05_INA226,
	EOL_N06_MOTOR_VALVE,
	EOL_N07_MODBUS_FLOW1,
	EOL_N08_MODBUS_FLOW2,
	EOL_N09_MODBUS_OVERFLOW,
	EOL_N10_NODE_LORA_TX,

	EOL_G01_SHARED_SPI,
	EOL_G02_RADIO0_IDENTITY,
	EOL_G03_RADIO0_RESET,
	EOL_G04_RADIO0_BUSY,
	EOL_G05_RADIO0_DIO1,
	EOL_G06_RADIO1_IDENTITY,
	EOL_G07_RADIO1_RESET,
	EOL_G08_RADIO1_BUSY,
	EOL_G09_RADIO1_DIO1,
	EOL_G10_RADIO0_RXTX_CONTROL,
	EOL_G11_RADIO1_RXTX_CONTROL,
	EOL_G12_RADIO0_TXRX,
	EOL_G13_RADIO1_TXRX,
	EOL_G14_RADIO_CS_ISOLATION,
	EOL_G15_DUAL_CHANNEL_LORA,

	EOL_S01_OLED,
	EOL_S02_USB_LOCAL_HOST,
	EOL_S03_OVERALL_RESULT,

	EOL_TEST_ID_COUNT
} EolTestId_t;

typedef struct
{
	EolTestId_t id;
	EolTestGroup_t group;
	const char *name;
} EolTestDefinition_t;

const EolTestDefinition_t *eol_registry_get(EolTestId_t id);
size_t eol_registry_count(void);
